dataset: 'RGB_image_single'
mode: 'visible' # 'visible', 'Fusion'
data:
  train_input_folder: datasets/datasets/pretrain_data #training model on dataset
  test_input_folder: datasets/data  #testing own data
  # input_folder: datasets/data  #testing own data
  # input_folder: datasets/pretrain_data
  image_size:
    h: 144 #1440
    w: 120 #1200
train:
  batch_size: 64
  train_ratio: 0.6
  num_epochs: 20
  pretrain: False
  lr: 0.01
  opt: 'adam' # 'sgd'
  momentum: 0.9
  weight_decay: 0.00001
  lr_scheduler: 'exp'
  gamma: 0.9
test:
  batch_size: 64
  train_ratio: 0.6
  num_epochs: 20
  pretrain: False
  lr: 0.01
  opt: 'adam' # 'sgd'
  momentum: 0.9
  weight_decay: 0.00001
  lr_scheduler: 'exp'
  gamma: 0.9
EC:
  layer_interest: ["conv1", "fc1", "fc2"] # ["conv1", "fc1", "fc2"]
  metric: 'minkowski'
  p: 2
  distance: [100000000000000]

